### ISSUE TITLE
[rxjs update] Generic type parameters for all operators were changed to accept the type of the source observable first. 

### ISSUE THREAD

**Issue by cubissimo** [gmarcos87/generator-firedux#2]
In rxjs 5.0.0-rc.1 the generic type parameters for all operators were changed to accept the type of the source observable first.

You will need to change the map operator call accordingly:

```
actions$
  .ofType(ProfileActions.PROFILE_UPDATE_PROFILE)
  .map<Action, string>(toPayload)
```

source: [stackoverflow](http://stackoverflow.com/questions/40074707/ngrx-supplied-parameters-do-not-match-any-signature-of-call-target)

**Comment by gmarcos87** [comment]
Thanks for your pull request. There I incorporated the changes and updated the dependencies. In a few hours is the new verison in NPM.
